### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Ph4nt0m-0ri0n** [samirsaci/ml-forecast-features-eng#1]
Hi, went through your code. I was wondering as to how I can implement prediction results in this code(since I'm new and am learning). Please help, thanks.

**Comment by CallmeAmmo** [comment]
Hi , went through your code. But i find one problem over hear , you have created lag features first and then you have split the data into training and testing . Doesn't it count as data leak as for the unseen data you would not have sales for all the unseen day then there this creation of lag would become a problem. Can you help with this and how could you create lag for the upcoming days for prediction as there are important features?

**Comment by CrasCris** [comment]
It would depend of your own dataset

**Comment by samirsaci** [comment]
> Hi, went through your code. I was wondering as to how I can implement prediction results in this code(since I'm new and am learning). Please help, thanks.

If you download this dataset, the official dataset of the kaggle M5 competition. You can run the code smoothly.
https://www.kaggle.com/competitions/m5-forecasting-accuracy
